services:
  gotokube:
    image: gotokube:dev
    container_name: gotokube-container
    environment:
      - WEB_ENABLE=true
      - WEB_LISTENINGADDR=:80
      - JWT_SECRET_KEY=JWT_TOKEN
      - KUBERNETES_ENABLE=false
      - KUBERNETES_CONFIGPATH=/root/.kube/config
    volumes:
      - ./kubeconfig:/root/.kube/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:80"