services:
  gotokube:
    image: gotokube:dev
    container_name: gotokube-container
    environment:
      - WEB_ENABLE=true
      - LISTENING_PORT=80
      - KUBE_ENABLE=true
      - KUBE_CONFIG_PATH=/root/config
    volumes:
      - ./k8sConfig:/root/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:80"