services:
  gotokube:
    image: gotokube:dev
    container_name: gotokube-container
    environment:
      - WEB_ENABLE=true
      - LISTENING_PORT=80
      - KUBE_ENABLE=false
      - KUBE_CONFIG_PATH=/root/.kube/config
    volumes:
      - /home/horonlee/.kube/config:/root/.kube/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:80"